# Site settings
title: Michael Milz
email: hallo@michamilz.de
description: > # ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://static.michamilz.de" # the base hostname & protocol for your site
twitter_username: micha_milz
github_username:  michamilz

# Build settings
markdown: kramdown
